server:
  port: 9012
spring:
  application:
    name: order-distribution-service
  cloud:
    stream:
      bindings:
        output: validatedPaymentInfo
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
